#!/bin/sh
usage='usage: qbe-tv src.ssa [tgt.ssa]

If two files are provided, qbe-tv checks that functions in the
second file refine functions in the first file with the same name.

If one file is provided, qbe-tv will optimize the entire module, and
then verify that functions in the optimized module refine those in the
original one.
'

set -e

if [ $# != 1 ] && [ $# != 2 ]
then
	echo "$usage"
	exit 1
fi

ssa1=$1
name1=$(basename "$1" .ssa)

if [ $# = 1 ]
then
	name2=$name1.tgt
	ssa2=$name2.ssa
	qbe -o /dev/null "$1" >"$ssa2"
else
	ssa2=$2
	name2=$(basename "$2" .ssa)
fi

bin/qbe2c "$ssa1" >"$name1.c"
bin/qbe2c "$ssa2" >"$name2.c"
clang -S -emit-llvm -o "$name1.ll" "$name1.c"
clang -S -emit-llvm -o "$name2.ll" "$name2.c"
alive-tv "$name1.ll" "$name2.ll"
